// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using serviceNow.Models;

namespace SNES.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20191204193221_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SNES.Models.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CategoryDetails");

                    b.Property<string>("CategoryName")
                        .IsRequired();

                    b.Property<string>("CategoryPicture");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<DateTime>("UpdatedOn");

                    b.HasKey("CategoryId");

                    b.HasAlternateKey("CategoryName")
                        .HasName("AlternateKey_CategoryName");

                    b.ToTable("SNES_CATEGORIES");
                });

            modelBuilder.Entity("SNES.Models.ReceiptModel", b =>
                {
                    b.Property<Guid>("RecID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CategoryId");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("LatiT");

                    b.Property<string>("LongT");

                    b.Property<byte[]>("RawPicture");

                    b.Property<double>("ReceiptAmount");

                    b.Property<DateTime>("ReceiptDate");

                    b.Property<double>("ReceiptTaxAmount");

                    b.Property<double>("ReceiptTipAmount");

                    b.Property<string>("StoreAddress");

                    b.Property<string>("StoreName");

                    b.Property<string>("StorePhoneNumber");

                    b.Property<DateTime>("UpdatedOn");

                    b.Property<string>("UserID");

                    b.Property<string>("rec_img_id");

                    b.HasKey("RecID");

                    b.ToTable("SNES_RECEIPTS");
                });

            modelBuilder.Entity("SNES.Models.User", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedTime");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.Property<DateTime>("UpdatedTime");

                    b.Property<string>("UserEmail")
                        .IsRequired();

                    b.Property<string>("UserName");

                    b.Property<string>("UserPicture");

                    b.HasKey("UserID");

                    b.HasAlternateKey("UserEmail")
                        .HasName("AlternateKey_UserEmail");

                    b.ToTable("SNES_USERS");
                });
#pragma warning restore 612, 618
        }
    }
}
